name = "temporary"
version = "1.0.0"

description = "Temporary files in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "temporary" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
exception = ">= 2.0.0 and < 3.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
